import { DuctNetworkGraph } from "../core/graph";
import type { NodeId } from "../core/nodes";
import { calculateLocalPressureLoss } from "./localLoss";
import type { NetworkPerformanceAnalysis } from "./networkPerformance";

export type AutomaticFittingType = "elbow" | "tee";

export interface AutomaticFittingResult {
  id: string;
  fittingType: AutomaticFittingType;
  nodeId: NodeId;
  nodeLabel: string;
  nodeIndex: number;
  downstreamComponentId: string;
  lossCoefficient: number;
  flowRateLps: number;
  velocityMps: number;
  pressureLossPa: number;
  isAutoGenerated: true;
  manualOverrideApplied: false;
}

const DEFAULT_ELBOW_LOSS_COEFFICIENT = 0.5;
const DEFAULT_TEE_LOSS_COEFFICIENT = 0.5;
const COLINEAR_TOLERANCE = 1e-6;

export function analyzeAutomaticRouteFittings(
  graph: DuctNetworkGraph,
  nodePath: NodeId[],
  routeComponentIdLookup: Map<string, string>,
  networkPerformance: NetworkPerformanceAnalysis
): AutomaticFittingResult[] {
  const automaticFittings: AutomaticFittingResult[] = [];

  for (let nodeIndex = 1; nodeIndex < nodePath.length - 1; nodeIndex += 1) {
    const previousNodeId = nodePath[nodeIndex - 1];
    const currentNodeId = nodePath[nodeIndex];
    const nextNodeId = nodePath[nodeIndex + 1];
    const connectedDuctSegments = graph
      .getConnectedComponents(currentNodeId)
      .filter((component) => component.type === "ductSegment");

    if (connectedDuctSegments.length < 2) {
      continue;
    }

    const fittingType = determineAutomaticFittingType(
      graph,
      previousNodeId,
      currentNodeId,
      nextNodeId,
      connectedDuctSegments.length
    );

    if (!fittingType) {
      continue;
    }

    const downstreamComponentId = routeComponentIdLookup.get(
      createNodePairKey(currentNodeId, nextNodeId)
    );

    if (!downstreamComponentId) {
      throw new Error(
        `No downstream component found for fitting node "${currentNodeId}".`
      );
    }

    const downstreamComponentResult =
      networkPerformance.componentResults.find(
        (componentResult) =>
          componentResult.componentId === downstreamComponentId
      );

    if (!downstreamComponentResult || downstreamComponentResult.velocityMps === null) {
      continue;
    }

    const lossCoefficient =
      fittingType === "elbow"
        ? DEFAULT_ELBOW_LOSS_COEFFICIENT
        : DEFAULT_TEE_LOSS_COEFFICIENT;
    const pressureLossPa = calculateLocalPressureLoss({
      lossCoefficient,
      densityKgPerM3: networkPerformance.airProperties.densityKgPerM3,
      velocityMps: downstreamComponentResult.velocityMps
    });
    const node = graph.getNode(currentNodeId);

    automaticFittings.push({
      id: `auto-fitting:${currentNodeId}:${fittingType}:${downstreamComponentId}`,
      fittingType,
      nodeId: currentNodeId,
      nodeLabel: node.metadata.label ?? node.id,
      nodeIndex,
      downstreamComponentId,
      lossCoefficient,
      flowRateLps: downstreamComponentResult.flowRateLps,
      velocityMps: downstreamComponentResult.velocityMps,
      pressureLossPa,
      isAutoGenerated: true,
      manualOverrideApplied: false
    });
  }

  return automaticFittings;
}

function determineAutomaticFittingType(
  graph: DuctNetworkGraph,
  previousNodeId: NodeId,
  currentNodeId: NodeId,
  nextNodeId: NodeId,
  connectedDuctCount: number
): AutomaticFittingType | null {
  if (connectedDuctCount >= 3) {
    return "tee";
  }

  if (connectedDuctCount === 2 && isElbowTurn(graph, previousNodeId, currentNodeId, nextNodeId)) {
    return "elbow";
  }

  return null;
}

function isElbowTurn(
  graph: DuctNetworkGraph,
  previousNodeId: NodeId,
  currentNodeId: NodeId,
  nextNodeId: NodeId
): boolean {
  const previousNode = graph.getNode(previousNodeId);
  const currentNode = graph.getNode(currentNodeId);
  const nextNode = graph.getNode(nextNodeId);
  const incomingX = currentNode.position.x - previousNode.position.x;
  const incomingY = currentNode.position.y - previousNode.position.y;
  const outgoingX = nextNode.position.x - currentNode.position.x;
  const outgoingY = nextNode.position.y - currentNode.position.y;
  const incomingLength = Math.hypot(incomingX, incomingY);
  const outgoingLength = Math.hypot(outgoingX, outgoingY);

  if (incomingLength === 0 || outgoingLength === 0) {
    return false;
  }

  const normalizedDotProduct =
    (incomingX * outgoingX + incomingY * outgoingY) /
    (incomingLength * outgoingLength);

  return Math.abs(normalizedDotProduct - 1) > COLINEAR_TOLERANCE;
}

export function createNodePairKey(nodeA: NodeId, nodeB: NodeId): string {
  return [nodeA, nodeB].sort().join("::");
}
